#!/usr/bin/env python3
"""
visualize_complicated_graph.py

Visualizes 'graph/edges_complicated.csv'.
Highlights the difference between Physical Rivers and Data-Driven Links.

- River Edges (Type 0): Blue, Solid
- Correlated Edges (Type 2): Purple, Dashed (representing statistical link)

Tooltips display the Correlation Coefficient and Elevation Delta.
"""

import pandas as pd
import folium
import os
from folium.plugins import MarkerCluster
from shapely import wkt
from shapely.geometry import mapping

# --- CONFIG ---
PWD = os.getcwd()
NODES_PATH = os.path.join(PWD, "graph", "nodes.csv")
EDGES_PATH = os.path.join(PWD, "graph", "edges_complicated.csv")
OUT_HTML = os.path.join(PWD, "map", "pakistan_complicated_network.html")

def main():
    print("--- Visualizing Complicated Graph ---")
    
    if not os.path.exists(EDGES_PATH):
        print(f"ERROR: {EDGES_PATH} not found. Run 'build_complicated_edges.py' first.")
        return

    nodes_df = pd.read_csv(NODES_PATH)
    edges_df = pd.read_csv(EDGES_PATH)
    print(f"Loaded {len(edges_df)} edges.")
    
    # Initialize Map
    center_lat = nodes_df['lat'].mean()
    center_lon = nodes_df['lon'].mean()
    m = folium.Map(location=[center_lat, center_lon], zoom_start=6, tiles="CartoDB positron")

    # Separate Features
    river_features = []
    complex_features = []

    print("Parsing geometries...")
    
    for _, row in edges_df.iterrows():
        try:
            # All edges in complicated_csv should have WKT generated by the builder
            if not isinstance(row['wkt'], str): continue
            
            geom = wkt.loads(row['wkt'])
            geom_json = mapping(geom)
            
            edge_type = int(row.get('edge_type', 0))
            
            # Build Rich Tooltip Properties
            props = {
                'id': str(row['edge_id']),
                'len': f"{float(row['length_km']):.1f}km",
            }
            
            if edge_type == 2:
                # Add Correlation specific data
                corr = float(row.get('correlation', 0))
                elev = float(row.get('elev_delta', 0))
                props['info'] = f"Corr: {corr:.2f} | dElev: {elev:.0f}m"
                props['type'] = "Correlated"
            else:
                props['info'] = "Physical Flow"
                props['type'] = "River"

            feature = {
                'type': 'Feature',
                'geometry': geom_json,
                'properties': props
            }
            
            if edge_type == 0:
                river_features.append(feature)
            elif edge_type == 2:
                complex_features.append(feature)
                
        except Exception as e:
            continue

    print(f"  > Rivers: {len(river_features)}")
    print(f"  > Correlated Links: {len(complex_features)}")

    # LAYER 1: Rivers (Blue)
    folium.GeoJson(
        {"type": "FeatureCollection", "features": river_features},
        name="Physical Rivers",
        style_function=lambda x: {
            'color': '#0077be', 
            'weight': 3, 
            'opacity': 0.9
        },
        tooltip=folium.GeoJsonTooltip(fields=['type', 'len', 'info'], aliases=['Type', 'Length', 'Details'])
    ).add_to(m)

    # LAYER 2: Correlated Edges (Purple)
    # Visualizing the "Hidden" connections
    folium.GeoJson(
        {"type": "FeatureCollection", "features": complex_features},
        name="Statistically Linked (Train Data)",
        style_function=lambda x: {
            'color': '#800080',   # Purple
            'weight': 1.5, 
            'opacity': 0.6,
            'dashArray': '5, 5'   # Dashed
        },
        tooltip=folium.GeoJsonTooltip(fields=['type', 'len', 'info'], aliases=['Type', 'Dist', 'Stats'])
    ).add_to(m)

    # Nodes Layer
    cluster = MarkerCluster(name="Nodes").add_to(m)
    for _, row in nodes_df.iterrows():
        folium.CircleMarker(
            location=[row['lat'], row['lon']],
            radius=2,
            color='#333',
            fill=True,
            popup=f"Node: {row['node_id']}"
        ).add_to(cluster)

    folium.LayerControl().add_to(m)
    m.save(OUT_HTML)
    print(f"Map saved to: {OUT_HTML}")

if __name__ == "__main__":
    main()